<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Shopping Platform <strong>Name</strong>' => '购物平台<strong>名字</strong>',
    'Of course, your new shopping platform needs a name. Please change the default name with one you like.' => '你的新购物平台需要一个名字，给它取一个你喜欢的名字吧。',
    'Next' => '下一步',
);