<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    '<strong>Congratulations</strong>. You\'re done.' => '恭喜你安装完成。',
    'Now you can click below link to view frontend or backend pages.' => '你可以点击下面链接，来浏览网站的前后台页面。',
    'Go to frontend' => '查看前端',
    'Go to Backend' => '登录后台',
);
