<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Install' => '安装向导',
    '<strong>Welcome</strong> to use Yii-Shop to build your own shopping platform' => '<strong>欢迎</strong> 使用Yii开源商城系统搭建你自己的购物平台！',
    'Next' => '下一步',
    'This wizard will install and configure your own shopping platform.<br><br>To continue, click Next.' => '该向导将引导你安装和配置你自己的购物平台。<br><br>点击下一步继续。',
];
