<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Username' => '用户名',
    'Password' => '密码',
    'Confirm Password' => '确认密码',
    'Email' => '邮箱',
    'Admin User Configuration' => '管理员配置',
    '<strong>Admin User</strong> Configuration' => '<strong>管理员</strong> 配置',
    'Below will create one admin user, you can use this user to manage your shopping platform.' => '接下来，将创建一个管理员帐户，你可以用此账户来管理你的购物平台。'
);