<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Goods Management' => '商品管理',
    'Goods Category' => '商品分类',
    'Goods List' => '商品列表',
    'Goods Type' => '商品类型',
    'Goods Specifications' => '商品规格',
    'Goods Attributes' => '商品属性',
    'Brand List' => '品牌列表',
    'Goods Comments' => '商品评论',
    'Goods Consultation' => '商品咨询',
    'Update' => '修改',
    'Delete' => '删除',
    'Create' => '添加',
    'Save' => '保存',
    'Search' => '筛选',
    'Operation' => '操作',
    'View' => '浏览',
    'Back to list' => '返回列表',
    'Brands' => '品牌列表',
    'Update Brand' => '修改品牌',
    'Create Brand' => '添加品牌',
    'Update Goods Category: ' => '修改分类: ',
    'Please Filter' => '请选择',
    'Goods Types' => '商品类型',
    'Create Goods Type' => '添加商品类型',
    'Update Goods Type: ' => '修改商品类型: ',
    'Create Spec Name' => '添加规格',
    'Spec Names' => '商品规格',
    'One line one item.' => '一行一个规格项',
    'Update Spec Name: '  => '修改规格: ',
    'Create Goods Attribute' => '创建商品属性',
    'Update Goods Attribute: ' => '修改商品属性: ',
    'One line one attribute item.' => '一行一个属性值项',
    'Create Goods' => '创建商品',
    'Goods' => '商品列表',
    'Update Goods: ' => '修改商品: ',
    'Yes' => '是',
    'No' => '否',
    'Category' => '分类',
    'Cart' => '购物车',
    'Settled Brand' => '入驻品牌',
    'Boutique' => '精品',
];
