<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Attr Name' => '属性名称',
    'Type ID' => '商品类型',
    'Attr Type' => '属性类型',
    'Attr Input Type' => '录入类型',
    'Attr Values' => '选项值',
    'Status' => '状态',
    'Order' => '排序',
    'Attr Index' => '关键字检索',
    'Text input' => '单行文本框',
    'Text area input' => '多行文本框',
    'Select list' => '选择列表',
    'Single attribute' => '单选属性',
    'Multiple attribute' => '多选属性',
    'Select values can not be blank.' => '选项值不能为空',
];
