<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cat ID' => '商品分类',
    'Sn' => '商品编号',
    'Name' => '商品名称',
    'Short Name' => '短名称',
    'Brand ID' => '品牌',
    'Stock' => '库存',
    'Comment Counts' => '评论次数',
    'Weight' => '重量',
    'Market Price' => '市场价',
    'Price' => '售价',
    'Cost Price' => '成本价',
    'Keywords' => '关键字',
    'Summary' => '概述',
    'Description' => '描述',
    'Original Img' => '封面图',
    'Is On Sale' => '上架状态',
    'Is Free Shipping' => '包邮',
    'On Sale At' => '上架时间',
    'Sort' => '排序',
    'Is Recommend' => '是否推荐',
    'Is New' => '是否新品',
    'Is Hot' => '是否热卖',
    'Last Update' => '最后更新时间',
    'Goods Type' => '商品类型',
    'Sales Sum' => '售出数量',
    'Album Images' => '相册图片',
    'New' => '新品',
    'Hot' => '热卖',
    'Recommend' => '推荐',
    'On Sale' => '上架',
    'Not On Sale' => '下架',
    'Tags' => '标签',
];
